import { useState } from 'react'
import {
  ChevronRight, Plus, ShieldCheck, UserCog,
} from 'lucide-react'

export default function AccessPage({ openModal, language = 'id' }) {
  const words = { 'Daftar peran':'Role list',Tambah:'Add',pengguna:'users','izin aktif':'active permissions',Module:'Module',Laporan:'Reports',Product:'Products',view:'view',create:'create',edit:'edit',delete:'delete',export:'export','Select All':'Select all',Reset:'Reset','Simpan permission':'Save permissions','Tambah role':'Add role','Nama role':'Role name','Salin permission dari':'Copy permissions from','Tidak ada':'None','Role berhasil ditambahkan':'Role added successfully','Role kustom tanpa deskripsi.':'Custom role without description.','Konfirmasi perubahan':'Confirm change','Pilih semua izin':'Select all permissions','Reset izin':'Reset permissions','Pilih semua izin untuk':'Select all permissions for','Reset izin untuk':'Reset permissions for','Simpan perubahan akses untuk':'Save access changes for','Perubahan akses akan diterapkan pada tampilan demo.':'The access changes will be applied in the demo.', 'Izin berhasil diperbarui':'Permission updated successfully','Semua izin berhasil dipilih':'All permissions selected','Izin berhasil direset':'Permissions reset successfully','Akses penuh seluruh sistem dan data.':'Full access to all system and data.','Kelola pengguna, outlet, dan pengaturan aplikasi.':'Manage users, outlets, and application settings.','Akses operasional untuk satu outlet.':'Operational access for one outlet.','Akses kasir untuk transaksi harian.':'Cashier access for daily transactions.','Kelola stok dan perpindahan barang.':'Manage stock and transfers.','Akses pembukuan dan laporan keuangan.':'Access bookkeeping and financial reports.' }
  const t = (text) => language === 'en' ? (words[text] || text) : text
  const modules = [
    'Dashboard', 'Transaksi', 'POS', 'Pembayaran', 'Membership',
    'Manajemen Stok', 'Akuntansi & Pembukuan', 'Menu', 'Kategori Menu',
    'User', 'Outlet', 'Log Aktivitas', 'Backup', 'Hak Akses', 'Setting',
  ]
  const perms = ['view','create','edit','delete','export']
  const baseRoles = [['Super Admin',1,'Akses penuh seluruh sistem dan data.'],['Admin',2,'Kelola pengguna, outlet, dan pengaturan aplikasi.'],['Manager',3,'Akses operasional untuk satu outlet.'],['Kasir',8,'Akses kasir untuk transaksi harian.'],['Staff Gudang',2,'Kelola stok dan perpindahan barang.'],['Accounting',2,'Akses pembukuan dan laporan keuangan.']]
  const build = (ri) => Object.fromEntries(modules.map((m,i)=>[m,perms.map((_,j)=>ri===0?true:j===0||i<3)]))
  const [roles, setRoles] = useState(baseRoles)
  const [role, setRole] = useState('Manager')
  const [matrix, setMatrix] = useState(() => Object.fromEntries(baseRoles.map(([r],ri)=>[r,build(ri)])))
  const current = roles.find(([r])=>r===role) || ['','','']
  const roleIndex = Math.max(roles.findIndex(([r])=>r===role), 0)
  const activeCount = modules.reduce((s,m)=>s+matrix[role][m].filter(Boolean).length,0)
  const toggle = (mi,pi) => openModal({type:'confirm',title:t('Konfirmasi perubahan'),message:matrix[role][modules[mi]][pi] ? t(`Nonaktifkan izin ${perms[pi]} untuk ${modules[mi]}?`) : t(`Aktifkan izin ${perms[pi]} untuk ${modules[mi]}?`),description:t('Perubahan akses akan diterapkan pada tampilan demo.'),success:t('Izin berhasil diperbarui'),onConfirm:()=>setMatrix(m=>({...m,[role]:{...m[role],[modules[mi]]:m[role][modules[mi]].map((v,j)=>j===pi?!v:v)}}))})
  const setAll = (val) => setMatrix(m=>({...m,[role]:Object.fromEntries(modules.map(m=>[m,perms.map(()=>val)]))}))
  const reset = () => setMatrix(m=>({...m,[role]:build(roleIndex)}))
  const addRole = () => openModal({type:'form',title:t('Tambah role'),kicker:'ROLE & PERMISSION',fields:[{name:'name',label:t('Nama role'),placeholder:'Supervisor',required:true},{name:'copy',label:t('Salin permission dari'),type:'select',options:[t('Tidak ada'),...roles.map(([r])=>r)]}],success:t('Role berhasil ditambahkan'),onConfirm:(data)=>{const name=(data.name||'').trim();if(!name||roles.some(([r])=>r.toLowerCase()===name.toLowerCase()))return;setRoles(rs=>[...rs,[name,0,t('Role kustom tanpa deskripsi.')]]);const copyFrom=data.copy&&data.copy!==t('Tidak ada')?data.copy:null;setMatrix(m=>({...m,[name]:copyFrom&&m[copyFrom]?JSON.parse(JSON.stringify(m[copyFrom])):Object.fromEntries(modules.map(mod=>[mod,perms.map(()=>false)]))}))}})
  const confirmAction = (title, message, handler, success) => openModal({type:'confirm',title:t(title),message:t(message),description:t('Perubahan akses akan diterapkan pada tampilan demo.'),success:t(success),onConfirm:handler})
  return <div className="module-page"><div className="access-grid"><aside><h3>{t('Daftar peran')} <button className="access-add" onClick={addRole}><Plus /> {t('Tambah')}</button></h3>{roles.map(([r,u])=><button className={role===r?'active':''} onClick={()=>setRole(r)} key={r}><span><UserCog /></span><div><strong>{r}</strong><small>{u} {t('pengguna')}</small></div><ChevronRight /></button>)}</aside><section><div className="permission-head"><div><h3>{current[0]}</h3><p>{t(current[2])}</p></div><span><ShieldCheck /> {activeCount} {t('izin aktif')}</span></div><div className="permission-matrix"><div className="permission-row head"><span>{t('Module')}</span>{perms.map(p=><span key={p}>{t(p)}</span>)}</div>{modules.map((module,i)=><div className="permission-row" key={module}><b>{t(module)}</b>{perms.map((p,j)=><label key={p}><input type="checkbox" checked={matrix[role][module][j]} onChange={()=>toggle(i,j)} /><i></i></label>)}</div>)}</div><div className="permission-actions"><button onClick={()=>confirmAction('Pilih semua izin',`Pilih semua izin untuk ${role}?`,()=>setAll(true),'Semua izin berhasil dipilih')}>{t('Select All')}</button><button onClick={()=>confirmAction('Reset izin',`Reset izin untuk ${role}?`,reset,'Izin berhasil direset')}>{t('Reset')}</button><button className="save-button" onClick={()=>confirmAction('Simpan permission',`Simpan perubahan akses untuk ${role}?`,()=>{},`Permission ${role} berhasil disimpan (${activeCount} izin aktif)`)}>{t('Simpan permission')}</button></div></section></div></div>
}
import '../styles/access.css'
