import { BookOpen, CreditCard, FileText, ReceiptText, UserRound, Users } from 'lucide-react'

const entityConfigs = {
  '/payment': { name:'Pembayaran', icon:CreditCard, stats:[['Total Pembayaran','Rp 48,6 jt'],['Berhasil','1.248'],['Menunggu','24'],['Gagal / Refund','12']], columns:['Invoice','Pelanggan','Metode','Total','Status'], rows:[['INV-20260820-001','Andi Wijaya','QRIS','Rp 162.000','Lunas'],['INV-20260820-002','Sarah Putri','Tunai','Rp 84.000','Lunas'],['INV-20260820-003','Kevin Lim','Debit','Rp 126.000','Menunggu']] },
  '/membership': { name:'Membership', icon:Users, stats:[['Total Member','1.284'],['Member Aktif','864'],['Total Points','284.600']], columns:['Member ID','Nama','Level','Point','Status'], rows:[['MBR-001','Andi Wijaya','Gold','1.240','Aktif'],['MBR-002','Sarah Putri','Platinum','2.860','Aktif'],['MBR-003','Kevin Lim','Silver','640','Aktif']], formFields:[{name:'name',label:'Nama member',required:true},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Telepon',placeholder:'0812...'},{name:'level',label:'Level',type:'select',options:['Silver','Gold','Platinum']},{name:'status',label:'Status',type:'select',options:['Aktif','Nonaktif']}] },
  '/users': { name:'User', icon:UserRound, cta:'Tambah user', resetAction:true, columns:['Username','Nama','Role','Outlet','Status'], rows:[['rina.kasir','Rina Maharani','Kasir','Kemang','Aktif'],['doni.manager','Doni Saputra','Manager','Cilandak','Aktif'],['siti.gudang','Siti Aminah','Staff Gudang','Kemang','Aktif']], formFields:[{name:'name',label:'Nama lengkap',required:true},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Nomor HP',placeholder:'0812...'},{name:'role',label:'Role',type:'select',options:['Admin','Manager','Kasir','Staff Gudang']},{name:'outlet',label:'Outlet',type:'select',options:['Kemang','Cilandak']},{name:'shift',label:'Shift',type:'select',options:['Pagi','Malam','Full']}] },
  '/accounting': { name:'Akuntansi & Pembukuan', icon:BookOpen, stats:[['Pendapatan','Rp 48,6 jt'],['Pengeluaran','Rp 11,4 jt'],['Laba Bersih','Rp 18,4 jt'],['Piutang / Hutang','Rp 4,8 jt']], columns:['Referensi','Kategori','Deskripsi','Nominal','Status'], rows:[['FIN-001','Pendapatan','Penjualan outlet','Rp 48.600.000','Tercatat'],['FIN-002','Operasional','Listrik & internet','Rp 2.400.000','Tercatat'],['FIN-003','Gaji','Gaji Agustus','Rp 8.200.000','Menunggu']] },
  '/transactions': { name:'Transaksi', icon:ReceiptText, stats:[['Hari ini','128'],['Lunas','116'],['Menunggu','8'],['Refund','4']], columns:['Invoice','Pelanggan','Outlet','Total','Status'], rows:[['INV-20260820-001','Andi Wijaya','Kemang','Rp 162.000','Lunas'],['INV-20260820-002','Sarah Putri','Cilandak','Rp 84.000','Lunas'],['INV-20260820-003','Kevin Lim','Kemang','Rp 126.000','Menunggu']] },
  '/orders': { name:'Taking Order', icon:FileText, stats:[['Order aktif','24'],['Dapur','12'],['Siap diantar','8'],['Selesai','186']], columns:['Order','Customer','Tipe','Total','Status'], rows:[['ORD-042','Meja 08','Dine in','Rp 162.000','Diproses'],['ORD-041','Sarah Putri','Takeaway','Rp 84.000','Siap'],['ORD-040','Meja 03','QR Order','Rp 126.000','Baru']] },
}


export default entityConfigs
