import { useState } from 'react'
import {
  ChevronDown, Download, ListFilter, Package, Plus, RefreshCcw, Search, Sparkles,
} from 'lucide-react'

const inventoryRows = [
  ['BRG-001', 'Biji Kopi House Blend', 'Bahan baku', '12 kg', 'Aman'], ['BRG-002', 'Susu UHT 1L', 'Bahan baku', '8 pcs', 'Menipis'], ['BRG-003', 'Cup 12 oz', 'Kemasan', '124 pcs', 'Aman'], ['BRG-004', 'Sirup Aren', 'Bahan baku', '4 botol', 'Menipis'], ['PRD-018', 'Croissant Butter', 'Produk jadi', '18 pcs', 'Aman'],
]

export default function InventoryPage({ openModal }) {
  const [tab,setTab]=useState('Produk')
  const tabs=['Produk','Kategori','Stock In','Stock Out','Adjustment','Stock Opname','Supplier']
  const addProduct=()=>openModal({type:'form',title:`Tambah ${tab}`,kicker:'MANAJEMEN STOK',size:'wide',image:['Produk','Kategori'].includes(tab),imageLabel:tab==='Kategori'?'Icon kategori':'Gambar produk',aspect:tab==='Produk'?4/3:1,fields:[{name:'name',label:`Nama ${tab}`,required:true},{name:'sku',label:'SKU / Reference',placeholder:'BRG-005'},{name:'category',label:'Kategori',type:'select',options:['Bahan baku','Produk jadi','Kemasan']},{name:'unit',label:'Satuan',type:'select',options:['pcs','kg','liter','box']},{name:'buy',label:'Harga beli',type:'number'},{name:'sell',label:'Harga jual',type:'number'},{name:'stock',label:'Stok awal',type:'number'},{name:'min',label:'Minimum stok',type:'number'},{name:'description',label:'Deskripsi',type:'textarea',wide:true}],success:`${tab} berhasil ditambahkan`})
  const action=(name,action)=>{if(action==='detail')openModal({type:'detail',title:'Detail produk',name,initials:name.slice(0,2).toUpperCase(),description:'Informasi produk dan stok',data:{SKU:'BRG-001',Kategori:'Bahan baku',Stok:'12 kg','Harga jual':'Rp 120.000',Status:'Aktif'}});if(action==='edit')addProduct();if(action==='delete')openModal({type:'confirm',title:'Hapus produk',name,message:`Hapus ${name}?`,success:'Produk berhasil dihapus'})}
  return <div className="module-page"><div className="inventory-kpis"><div><Package /><span><small>Total produk</small><strong>284</strong></span></div><div><Sparkles /><span><small>Stok menipis</small><strong>8 produk</strong></span></div><div><RefreshCcw /><span><small>Opname bulan ini</small><strong>3 aktivitas</strong></span></div></div><div className="module-tabs inventory-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="data-card"><div className="data-toolbar"><label><Search /><input placeholder={`Cari data ${tab.toLowerCase()}`} /></label><button><ListFilter /> Semua kategori <ChevronDown /></button><button><RefreshCcw /> Refresh</button><button><Download /> Export</button><button className="primary" onClick={addProduct}><Plus /> Tambah {tab}</button></div>{tab==='Produk'?<div className="data-table inventory-table"><div className="data-row data-head"><span>Produk</span><span>Kategori</span><span>Stok</span><span>Status</span><span>Aksi</span></div>{inventoryRows.map(([sku,name,cat,stock,status])=><div className="data-row" key={sku}><span><i className="table-thumb"></i><b>{name}<small>{sku}</small></b></span><span>{cat}</span><span><b>{stock}</b></span><span><em className={status==='Menipis'?'warning':''}>{status}</em></span><span><RowActions onAction={(a)=>action(name,a)} /></span></div>)}</div>:<div className="data-table inventory-subtable"><div className="data-row data-head"><span>Reference</span><span>Data</span><span>Qty / Status</span><span>Tanggal</span><span>Aksi</span></div>{[['REF-202608-001',`${tab} Kopi Susu`,'24 pcs','20 Agu 2026'],['REF-202608-002',`${tab} Matcha`,'12 pcs','19 Agu 2026'],['REF-202608-003',`${tab} Kemasan`,'Aktif','18 Agu 2026']].map(r=><div className="data-row" key={r[0]}>{r.map(v=><span key={v}>{v}</span>)}<span><RowActions onAction={(a)=>action(r[1],a)} /></span></div>)}</div>}<div className="table-footer"><span>Menampilkan 1–5 dari 284 data</span><div><button disabled>←</button><b>1</b><button>2</button><button>3</button><button>→</button></div></div></div></div>
}
import RowActions from '../components/RowActions'
import '../styles/inventory.css'
