import { useState } from 'react'
import {
  Download, Plus,
} from 'lucide-react'

export default function OutletPage({ openModal }) {
  const [tab, setTab] = useState('Promo & Diskon')
  const tabs = ['Konfigurasi', 'Tax & Service', 'Item Outlet', 'Payment', 'Kasir', 'Promo & Diskon', 'Paket', 'Catatan Orderan', 'Waiter']
  const add=()=>openModal({type:'form',title:`Tambah ${tab}`,kicker:'PENGATURAN OUTLET',size:'wide',image:['Item Outlet','Paket'].includes(tab),aspect:4/3,fields:[{name:'name',label:`Nama ${tab}`,required:true},{name:'code',label:'Kode',placeholder:'OUT-001'},{name:'value',label:'Nilai / Harga',type:'number'},{name:'status',label:'Status',type:'select',options:['Aktif','Nonaktif']},{name:'note',label:'Catatan',type:'textarea',wide:true}],success:`${tab} berhasil ditambahkan`})
  const rowAction=(name,a)=>a==='delete'?openModal({type:'confirm',title:`Hapus ${tab}`,message:`Apakah Anda yakin ingin menghapus ${name}?`,success:`${tab} berhasil dihapus`}):a==='detail'?openModal({type:'detail',title:`Detail ${tab}`,name,initials:name.slice(0,2).toUpperCase(),data:{Outlet:'Kemang',Status:'Aktif',Dibuat:'20 Agustus 2026'}}):add()
  const demoRows={Konfigurasi:[['CFG-01','Jam operasional','08:00–22:00']], 'Tax & Service':[['TAX-11','PPN','11%'],['SRV-05','Service charge','5%']], 'Item Outlet':[['ITM-001','Kopi Susu Aren','Rp 22.000'],['ITM-002','Matcha Latte','Rp 26.000']],Payment:[['PAY-01','QRIS','Aktif'],['PAY-02','Cash','Aktif']],Kasir:[['USR-01','Rina Kasir','Aktif']],Paket:[['PKT-01','Paket Berdua','Rp 78.000']], 'Catatan Orderan':[['NOTE-01','Tidak pedas','Aktif']],Waiter:[['WTR-01','Dimas','Shift pagi']]}
  const rows=demoRows[tab]||[]
  return <div className="module-page"><div className="module-title"><button onClick={()=>openModal({type:'form',title:'Tambah outlet',kicker:'OUTLET',size:'wide',image:true,fields:[{name:'name',label:'Nama outlet'},{name:'code',label:'Kode outlet'},{name:'manager',label:'Manager'},{name:'phone',label:'Telepon'},{name:'address',label:'Alamat',type:'textarea',wide:true}],success:'Outlet berhasil ditambahkan'})}><Plus /> Tambah outlet</button></div><div className="settings-card"><div className="settings-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==='Promo & Diskon'?<><div className="subtabs"><button className="active">Potongan belanja</button><button>Promo item</button><button>Diskon</button></div><div className="data-toolbar"><button className="primary" onClick={add}><Plus /> Tambah promo</button><button><Download /> Export</button></div><div className="data-table promo-table with-actions"><div className="data-row data-head"><span>Kode promo</span><span>Nama promo</span><span>Tanggal mulai</span><span>Status</span><span>Aksi</span></div>{[['PRO-260801','Promo Kemerdekaan','01 Agustus 2026'],['PRO-260724','Paket Hemat Berdua','24 Juli 2026'],['PRO-260615','Diskon Member Gold','15 Juni 2026']].map(r=><div className="data-row" key={r[0]}><span><b>{r[0]}</b></span><span>{r[1]}</span><span>{r[2]}</span><span><em>Aktif</em></span><span><RowActions onAction={(a)=>rowAction(r[1],a)} /></span></div>)}</div></>:<><div className="setting-demo-head"><div><h3>{tab}</h3><p>Demo pengaturan {tab.toLowerCase()} untuk outlet terpilih.</p></div><button onClick={add}><Plus /> Tambah data</button></div><div className="data-table outlet-demo-table"><div className="data-row data-head"><span>Kode</span><span>Nama / Pengaturan</span><span>Nilai</span><span>Status</span><span>Aksi</span></div>{rows.map(r=><div className="data-row" key={r[0]}><span><b>{r[0]}</b></span><span>{r[1]}</span><span>{r[2]}</span><span><em>Aktif</em></span><span><RowActions onAction={(a)=>rowAction(r[1],a)} /></span></div>)}</div></>}</div></div>
}
import RowActions from '../components/RowActions'
import '../styles/outlet.css'
