import { useState } from 'react'
import ImageUploaderWithCrop from '../components/ImageUploaderWithCrop'
import ToggleSettings from '../components/ToggleSettings'

export default function ProfilePage({ notify }) {
  const [tab,setTab]=useState('Personal Information')
  const [photo,setPhoto]=useState('')
  const tabs=['Personal Information','Security','Preferences','Login Activity']
  return <div className="module-page"><div className="profile-hero"><span>{photo?<img src={photo} alt="Admin Demo"/>:'AD'}</span><div><h2>Admin Demo</h2><p>Super Admin · Outlet Kemang</p></div><em>Online</em></div><div className="profile-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="profile-card">{tab==='Security'?<div className="setting-form"><div className="setting-section-title"><h3>Ubah password</h3><p>Password pada demo hanya disimpan sementara.</p></div><div className="crud-fields"><label>Current Password<input type="password" /></label><label>New Password<input type="password" /></label><label>Confirm Password<input type="password" /></label></div><button className="save-button" onClick={()=>notify('Password demo berhasil diperbarui','success')}>Simpan password</button></div>:tab==='Login Activity'?<div className="data-table login-table"><div className="data-row data-head"><span>Device</span><span>Lokasi</span><span>Waktu</span><span>Status</span></div>{[['Chrome · Windows','Jakarta, Indonesia','Sekarang','Aktif'],['Safari · iPhone','Jakarta, Indonesia','18 Agu 2026','Selesai']].map(r=><div className="data-row" key={r[2]}>{r.map((v,i)=><span key={v}>{i===3?<em>{v}</em>:v}</span>)}</div>)}</div>:tab==='Preferences'?<ToggleSettings title="Preferensi" items={['Notifikasi email','Notifikasi WhatsApp','Mode ringkas','Suara POS']} />:<div className="setting-form"><div className="setting-section-title"><h3>Informasi personal</h3><p>Perbarui data profile yang digunakan di aplikasi.</p></div><ImageUploaderWithCrop label="Foto profile" aspect={1} value={photo} onChange={(v)=>{setPhoto(v);notify('Foto profile berhasil diperbarui','success')}} /><div className="crud-fields"><label>Nama<input defaultValue="Admin Demo"/></label><label>Email<input defaultValue="admin@gmail.com"/></label><label>Telepon<input defaultValue="0812 3456 7890"/></label><label>Tanggal lahir<input type="date" defaultValue="1990-08-20"/></label><label className="wide">Alamat<textarea defaultValue="Jakarta Selatan"/></label></div><button className="save-button" onClick={()=>notify('Profile berhasil diperbarui','success')}>Simpan profile</button></div>}</div></div>
}
import '../styles/profile.css'
