import { useState } from 'react'
import ImageUploaderWithCrop from '../components/ImageUploaderWithCrop'
import ToggleSettings from '../components/ToggleSettings'

export default function ProfilePage({ notify }) {
  const [tab,setTab]=useState('Personal Information')
  const [photo,setPhoto]=useState('')
  const tabs=['Personal Information','Security','Preferences']
  return <div className="module-page"><div className="profile-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="profile-card">{tab==='Security'?<div className="setting-form"><div className="setting-section-title"><h3>Ubah password</h3><p>Password pada demo hanya disimpan sementara.</p></div><div className="crud-fields"><label>Current Password<input type="password" /></label><label>New Password<input type="password" /></label><label>Confirm Password<input type="password" /></label></div><button className="save-button" onClick={()=>notify('Password demo berhasil diperbarui','success')}>Simpan password</button></div>:tab==='Preferences'?<div className="prefs-stack"><ToggleSettings title="Preferensi" items={['Notifikasi email','Notifikasi WhatsApp','Mode ringkas','Suara POS']} /><div className="appearance-options"><h3>Tampilan aplikasi</h3>{['Light','Dark','System'].map((t,i)=><button className={i===0?'active':''} key={t}><span className={`theme-thumb ${t.toLowerCase()}`}></span><b>{t}</b><small>{i===2?'Ikuti perangkat':`Gunakan tema ${t.toLowerCase()}`}</small></button>)}<button className="save-button" onClick={()=>notify('Tampilan aplikasi disimpan','success')}>Simpan tampilan</button></div></div>:<div className="setting-form"><div className="setting-section-title"><h3>Informasi personal</h3><p>Perbarui data profile yang digunakan di aplikasi.</p></div><ImageUploaderWithCrop label="Foto profile" aspect={1} value={photo} onChange={(v)=>{setPhoto(v);notify('Foto profile berhasil diperbarui','success')}} /><div className="crud-fields"><label>Nama<input defaultValue="Admin Demo"/></label><label>Email<input defaultValue="admin@gmail.com"/></label><label>Telepon<input defaultValue="0812 3456 7890"/></label><label>Tanggal lahir<input type="date" defaultValue="1990-08-20"/></label></div><button className="save-button" onClick={()=>notify('Profile berhasil diperbarui','success')}>Simpan profile</button></div>}</div></div>
}
import '../styles/profile.css'
