import { useState } from 'react'
import Logo from '../components/Logo'
import {
  Download, Plus, RefreshCcw, Save, Search,
} from 'lucide-react'
import ImageUploaderWithCrop from '../components/ImageUploaderWithCrop'
import ToggleSettings from '../components/ToggleSettings'

export default function SettingsPage({ openModal, notify }) {
  const [tab,setTab]=useState('General')
  const [categories,setCategories]=useState([['CAT-01','Kopi','Minuman berbasis kopi','12','Aktif'],['CAT-02','Makanan','Menu makanan utama','18','Aktif'],['CAT-03','Snack','Camilan dan pastry','9','Aktif']])
  const [menus,setMenus]=useState([['MNU-01','Kopi Susu Aren','Kopi','Rp 22.000','Aktif'],['MNU-02','Matcha Latte','Minuman','Rp 26.000','Aktif'],['MNU-03','Croissant Butter','Snack','Rp 18.000','Aktif']])
  const tabs=['General','Kategori','Menu POS','POS Setting','Receipt','Notification','Appearance']
  const addCategory=()=>openModal({type:'form',title:'Tambah kategori',kicker:'SETTING KATEGORI',image:true,imageLabel:'Icon kategori',aspect:1,fields:[{name:'name',label:'Nama kategori',required:true},{name:'description',label:'Deskripsi',type:'textarea',wide:true},{name:'status',label:'Status',type:'select',options:['Aktif','Nonaktif']}],success:'Kategori berhasil ditambahkan',onConfirm:(data)=>setCategories(rows=>[[`CAT-0${rows.length+1}`,data.name,data.description||'-','0',data.status],...rows])})
  const addMenu=()=>openModal({type:'form',title:'Tambah menu POS',kicker:'SETTING MENU',size:'wide',image:true,imageLabel:'Gambar menu',aspect:4/3,fields:[{name:'name',label:'Nama menu',required:true},{name:'category',label:'Kategori',type:'select',options:['Kopi','Minuman','Makanan','Snack']},{name:'price',label:'Harga',type:'number'},{name:'order',label:'Sort order',type:'number'},{name:'description',label:'Deskripsi',type:'textarea',wide:true},{name:'status',label:'Status',type:'select',options:['Aktif','Nonaktif']}],success:'Menu berhasil ditambahkan',onConfirm:(data)=>setMenus(rows=>[[`MNU-0${rows.length+1}`,data.name,data.category,`Rp ${Number(data.price||0).toLocaleString('id-ID')}`,data.status],...rows])})
  const action=(type,row,a)=>{if(a==='detail')openModal({type:'detail',title:`Detail ${type}`,name:row[1],initials:row[1].slice(0,2).toUpperCase(),data:{Kode:row[0],Nama:row[1],Status:row.at(-1)}});if(a==='edit')(type==='kategori'?addCategory:addMenu)();if(a==='delete')openModal({type:'confirm',title:`Hapus ${type}`,message:`Hapus ${row[1]}?`,success:`${type} berhasil dihapus`,onConfirm:()=>type==='kategori'?setCategories(r=>r.filter(x=>x[0]!==row[0])):setMenus(r=>r.filter(x=>x[0]!==row[0]))})}
  return <div className="module-page settings-page"><div className="module-title"><button onClick={()=>notify('Pengaturan berhasil disimpan','success')}><Save /> Simpan</button></div><div className="settings-layout"><aside>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</aside><section>{tab==='General'&&<div className="setting-form"><div className="setting-section-title"><h3>Informasi bisnis</h3><p>Informasi utama yang tampil pada aplikasi dan struk.</p></div><ImageUploaderWithCrop label="Logo bisnis" aspect={1} value="" onChange={()=>notify('Logo berhasil di-crop','success')} /><div className="crud-fields"><label>Nama Bisnis<input defaultValue="BukaNota Coffee" /></label><label>Telepon<input defaultValue="021 555 0199" /></label><label>Email<input defaultValue="hello@bukanota.id" /></label><label>Currency<select><option>IDR — Rupiah</option></select></label><label>Timezone<select><option>Asia/Jakarta</option></select></label><label>Language<select><option>Bahasa Indonesia</option></select></label><label className="wide">Alamat<textarea defaultValue="Jl. Kemang Raya No. 18, Jakarta Selatan" /></label></div></div>}{tab==='Kategori'&&<CrudSettingTable title="Setting kategori" description="Kelola kategori yang tampil pada POS." button="Tambah kategori" rows={categories} columns={['Kode','Nama kategori','Deskripsi','Jumlah item','Status']} onAdd={addCategory} onAction={(r,a)=>action('kategori',r,a)} />}{tab==='Menu POS'&&<CrudSettingTable title="Setting menu POS" description="Tambah menu, upload gambar, crop, dan atur urutan." button="Tambah menu" rows={menus} columns={['Kode','Nama menu','Kategori','Harga','Status']} onAdd={addMenu} onAction={(r,a)=>action('menu',r,a)} />}{tab==='POS Setting'&&<ToggleSettings title="Pengaturan Point of Sale" items={['Tax 11%','Service charge 5%','Auto print receipt','Allow discount','Allow refund','Stock validation']} />}{tab==='Receipt'&&<div className="receipt-setting"><div><ToggleSettings title="Elemen struk" items={['Tampilkan logo','Tampilkan customer','Tampilkan kasir','Tampilkan pajak']} /></div><div className="receipt-preview"><Logo /><h4>BukaNota Coffee</h4><p>Jl. Kemang Raya No. 18</p><hr/><span>2 × Kopi Susu <b>44.000</b></span><span>1 × Croissant <b>18.000</b></span><hr/><strong>Total <b>Rp 62.000</b></strong><small>Terima kasih sudah berkunjung</small></div></div>}{tab==='Notification'&&<ToggleSettings title="Notifikasi" items={['Low stock','Transaksi baru','Backup success','Failed payment','User login']} />}{tab==='Appearance'&&<div className="appearance-options"><h3>Tampilan aplikasi</h3>{['Light','Dark','System'].map((t,i)=><button className={i===0?'active':''} key={t}><span className={`theme-thumb ${t.toLowerCase()}`}></span><b>{t}</b><small>{i===2?'Ikuti perangkat':`Gunakan tema ${t.toLowerCase()}`}</small></button>)}</div>}</section></div></div>
}

function CrudSettingTable({ title,description,button,rows,columns,onAdd,onAction }) {
  return <div><div className="setting-demo-head"><div><h3>{title}</h3><p>{description}</p></div><button onClick={onAdd}><Plus />{button}</button></div><div className="data-toolbar"><label><Search /><input placeholder={`Cari ${title.toLowerCase()}`} /></label><button><RefreshCcw /> Refresh</button><button><Download /> Export</button></div><div className="data-table settings-crud-table"><div className="data-row data-head">{columns.map(c=><span key={c}>{c}</span>)}<span>Aksi</span></div>{rows.map(r=><div className="data-row" key={r[0]}>{r.map((v,i)=><span key={`${r[0]}-${i}`}>{i===0?<b>{v}</b>:i===r.length-1?<em>{v}</em>:v}</span>)}<span><RowActions onAction={(a)=>onAction(r,a)} /></span></div>)}</div></div>
}
import RowActions from '../components/RowActions'
import '../styles/settings.css'
