import {
  ArrowRight, BookOpen, Check, ChevronDown, CreditCard, Crown, FileText, Gift, Grid2X2, Package, Plus, ReceiptText, Search, Users,
} from 'lucide-react'

export default function AnimatedVisual({ type = 'pos', compact = false }) {
  if (type === 'dashboard') return <div className="animated-ui dashboard-ui"><div className="aui-top"><span><Grid2X2 /> Dashboard</span><i></i><i></i></div><div className="aui-metrics"><b><small>Penjualan</small>Rp 48,6 jt<em>+12,8%</em></b><b><small>Transaksi</small>1.284<em>+8,2%</em></b><b><small>Laba kotor</small>Rp 18,4 jt<em>+14,2%</em></b></div><div className="aui-chart"><div className="chart-line"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><span>Tren penjualan · 30 hari</span></div><div className="aui-activity"><span></span><div><b>Outlet Kemang</b><small>Kontribusi tertinggi bulan ini</small></div><em>44%</em></div></div>
  if (type === 'stock') return <div className="animated-ui stock-ui"><div className="aui-top"><span><Package /> Inventori</span><button><Plus /> Produk</button></div><div className="stock-stats"><b><small>Total produk</small>284</b><b><small>Stok menipis</small>8</b></div>{[['Biji Kopi House Blend','12 kg','Aman'],['Susu UHT 1L','8 pcs','Menipis'],['Cup 12 oz','124 pcs','Aman'],['Sirup Aren','4 botol','Menipis']].map((r,i)=><div className="stock-anim-row" style={{'--delay':`${i*.1}s`}} key={r[0]}><i></i><span><b>{r[0]}</b><small>Bahan baku</small></span><strong>{r[1]}</strong><em className={r[2]==='Menipis'?'warn':''}>{r[2]}</em></div>)}</div>
  if (type === 'books') return <div className="animated-ui books-ui"><div className="aui-top"><span><BookOpen /> Laba rugi</span><button>Bulan ini <ChevronDown /></button></div><div className="profit-animated"><small>Laba bersih</small><strong>Rp 18.420.000</strong><em>+14,2% dari bulan lalu</em></div>{[['Pendapatan','100%','Rp 48,6 jt'],['Harga pokok','39%','Rp 18,7 jt'],['Biaya operasional','24%','Rp 11,4 jt']].map((r,i)=><div className="finance-bar" key={r[0]}><span>{r[0]}<b>{r[2]}</b></span><i><em style={{width:r[1],'--delay':`${i*.15}s`}}></em></i></div>)}</div>
  if (type === 'payment') return <div className="animated-ui payment-ui"><div className="aui-top"><span><CreditCard /> Pembayaran</span><b>Rp 162.000</b></div><div className="payment-options">{[['Tunai','Rp'],['QRIS','QR'],['Debit','DB'],['E-Wallet','EW']].map((p,i)=><button className={i===1?'active':''} key={p[0]}><i>{p[1]}</i><span>{p[0]}</span>{i===1&&<Check />}</button>)}</div><div className="payment-progress"><i></i><span>Menunggu pembayaran QRIS…</span></div><button className="visual-primary">Konfirmasi pembayaran <ArrowRight /></button></div>
  if (type === 'order') return <div className="animated-ui order-ui"><div className="aui-top"><span><FileText /> Taking Order</span><button><Plus /> Pesanan</button></div>{[['Meja 08','3 item','Diproses'],['Meja 12','5 item','Siap'],['Takeaway #42','2 item','Baru']].map((r,i)=><div className="order-card" style={{'--delay':`${i*.12}s`}} key={r[0]}><b>{r[0]}</b><small>{r[1]}</small><em>{r[2]}</em><div><span style={{width:`${[68,100,34][i]}%`}}></span></div></div>)}</div>
  if (type === 'member') return <div className="animated-ui member-ui"><div className="member-hero"><span>RA</span><div><b>Raisa Amelia</b><small>Gold Member · sejak 2024</small></div><Crown /></div><div className="member-points"><small>Poin tersedia</small><strong>1.240</strong><span>+180 bulan ini</span></div><div className="member-reward"><Gift /><div><b>Gratis Kopi Susu</b><small>Tukar dengan 1.000 poin</small></div><button>Tukar</button></div></div>
  return <div className={`animated-ui pos-ui ${compact ? 'compact' : ''}`}><div className="pos-anim-top"><span>BN</span><b>Kasir Utama</b><i></i><small>Outlet Kemang</small></div><div className="pos-anim-body"><aside>{[Grid2X2,ReceiptText,Package,Users].map((Icon,i)=><span className={i===0?'active':''} key={i}><Icon /></span>)}</aside><section><div className="pos-anim-heading"><div><small>Selamat pagi</small><b>Mulai transaksi</b></div><Search /></div><div className="pos-anim-tabs"><b>Semua</b><span>Kopi</span><span>Makanan</span></div><div className="pos-anim-products">{[['KS','Kopi Susu','22.000'],['AM','Americano','18.000'],['ML','Matcha Latte','26.000'],['RB','Rice Bowl','32.000']].map((p,i)=><div style={{'--delay':`${i*.1}s`}} key={p[0]}><i>{p[0]}</i><b>{p[1]}</b><small>Rp {p[2]}</small></div>)}</div></section><aside className="pos-anim-cart"><b>Pesanan #1042</b><small>Dine in · Meja 08</small><p><span>2 × Kopi Susu</span><b>44.000</b></p><p><span>1 × Americano</span><b>18.000</b></p><div><span>Total</span><b>Rp 62.000</b></div><button>Bayar sekarang <ArrowRight /></button></aside></div></div>
}
