import { useEffect, useState } from 'react'
import {
  Save, Trash2, X,
} from 'lucide-react'
import ImageUploaderWithCrop from './ImageUploaderWithCrop'

export default function AppModal({ modal, onClose, notify }) {
  const [image, setImage] = useState(modal.initial?.image || '')
  useEffect(() => { const escape = (e) => e.key === 'Escape' && onClose(); addEventListener('keydown', escape); return () => removeEventListener('keydown', escape) }, [onClose])
  const submit = (e) => { e.preventDefault(); modal.onConfirm?.(Object.fromEntries(new FormData(e.currentTarget)), image); notify(modal.success || 'Data berhasil disimpan', 'success'); onClose() }
  return <div className="app-modal-overlay" onMouseDown={(e) => e.target === e.currentTarget && modal.type !== 'confirm' && onClose()}><div className={`app-modal ${modal.size || ''}`} role="dialog" aria-modal="true"><div className="app-modal-header"><div><h3>{modal.title}</h3>{modal.subtitle && <p>{modal.subtitle}</p>}</div><button onClick={onClose}><X /></button></div>{modal.type === 'detail' && <div className="detail-modal-body"><div className="detail-identity"><span>{modal.initials || 'BN'}</span><div><h4>{modal.name}</h4><p>{modal.description || 'Detail informasi data'}</p></div></div><div className="detail-grid">{Object.entries(modal.data || {}).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></div>}{modal.type === 'confirm' && <div className="confirm-modal-body"><span className="danger-icon"><Trash2 /></span><h4>{modal.message || 'Apakah Anda yakin ingin menghapus data ini?'}</h4><p>{modal.description || 'Tindakan ini tidak dapat dibatalkan pada sesi demo.'}</p></div>}{modal.type === 'form' && <form id="app-modal-form" className="crud-form" onSubmit={submit}>{modal.image && <ImageUploaderWithCrop label={modal.imageLabel || 'Gambar'} aspect={modal.aspect || 1} value={image} onChange={setImage} />}<div className="crud-fields">{(modal.fields || []).map(field => <label className={field.wide ? 'wide' : ''} key={field.name}>{field.label}{field.type === 'select' ? <select name={field.name} defaultValue={field.value || ''}>{(field.options || []).map(option => <option key={option}>{option}</option>)}</select> : field.type === 'textarea' ? <textarea name={field.name} defaultValue={field.value || ''} placeholder={field.placeholder} /> : <input name={field.name} type={field.type || 'text'} defaultValue={field.value || ''} placeholder={field.placeholder} required={field.required} />}</label>)}</div></form>}<div className="app-modal-footer"><button onClick={onClose}>Batal</button>{modal.type === 'confirm' ? <button className="danger" onClick={() => { modal.onConfirm?.(); notify(modal.success || 'Data berhasil dihapus', 'success'); onClose() }}><Trash2 /> Hapus</button> : modal.type === 'detail' ? <button className="primary" onClick={onClose}>Selesai</button> : <button className="primary" form="app-modal-form" type="submit"><Save /> Simpan</button>}</div></div></div>
}
import '../styles/modal.css'
